### ISSUE TITLE
Password reset issues

### ISSUE THREAD

**Issue by nickjer** [OSC/osc-connect#50]
Per Bud's complaints:

>
I recently had to change my password.  So every time I invoke any part of the VFT app it asks for my password again.  I fixed it as you discussed before.  Also – for future users – when the password is changed it would be nice to not have to do this – or warn the user with directions?

This has been a re-occurring issue for him.

**Comment by brianmcmichael** [comment]
The old password is saved in OSC Connect and it's using that to create the tunnel.

Bud will need to update his password in OSC connect and try again.

I can review the process by which the password is saved and make it more aggressive.

**Comment by brianmcmichael** [comment]
Added a listener to update the saved password on text change at https://github.com/OSC/osc-connect/commit/66f1de9c885a5c3938ca23047867fee24e4db1f0
